 #ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.9.0 */
/* https://github.com/olo2000pm/Virtuoso-ESP32-YoRadio */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */
/* !!! Attention !!! */
/* !!! Do not be alarmed by some #defines missing. Default values are not included in this file. !!! */
/* !!! Values of 255 must be edited before using (except I2S_DOUT 255 which is used to disable I2S Sound). !!! */

#define ARDUINO_ESP32S3_DEV

#define CONFIG_ASYNC_TCP_RUNNING_CORE 1

#ifdef NETSERVER_ENABLE_MDNS
#undef NETSERVER_ENABLE_MDNS
#endif
#define NETSERVER_ENABLE_MDNS 0

#define L10N_LANGUAGE PL

#define DSP_MODEL DSP_LCD800

#ifdef RTC_MODULE
#undef RTC_MODULE
#endif
#define RTC_MODULE RTC_MODULE_UNDEFINED
#ifdef RTC_SDA
#undef RTC_SDA
#endif
#define RTC_SDA 255
#ifdef RTC_SCL
#undef RTC_SCL
#endif
#define RTC_SCL 255

#define I2S_LRC 11
#define I2S_DOUT 13
#define I2S_BCLK 12
#define I2S_MCLK 255
#define I2S_INTERNAL false


#define ENC_BTNR 255
#define ENC_BTNL 255
#define ENC_BTNB 255

#define ENC2_BTNR 255
#define ENC2_BTNL 255
#define ENC2_BTNB 255

#define IR_PIN			6
#define IR_TIMEOUT      50

#define BT_RELAY_PIN 255

#define BT_MUTE_PIN 255
#define BT_KEY_PIN 255

// VU METER STYLE
// Now controlled via Web Interface (System Settings)
// #define VU_STYLE_PARALLEL - Deprecated, use GUI

// dodać jeśli chcesz wyłaczyć diodę RGB:
#define USE_BUILTIN_LED false
#define LED_BUILTIN_S3 255

#define WAKE_PIN 255

// GT911 touch (Waveshare ESP32-S3-Touch-LCD-7)
#define TS_MODEL TS_MODEL_GT911
#define TS_SDA 8
#define TS_SCL 9
#define TS_INT 4
#define TS_RST 255

#define BITRATE_FULL false //---wyłączenie wskaznika BitrateFull (używamy prostego)
#define EXT_WEATHER false //---skrocone informacje pogodowe
#define SDC_CS 255

#define AUDIOBUFFER_MULTIPLIER2 64
#define DMA_BUFCOUNT 12
#define DMA_BUFCOUNT_PSRAM 24
#define AUDIO_PREFILL_FRAMES 2

#define COLOR_BACKGROUND 5, 10, 26
#define COLOR_STATION_NAME 0, 255, 255
#define COLOR_STATION_BG 8, 18, 48
#define COLOR_STATION_FILL 5, 10, 26
#define COLOR_SNG_TITLE_1 255, 255, 255
#define COLOR_SNG_TITLE_2 160, 220, 255
#define COLOR_WEATHER 255, 200, 0
#define COLOR_VU_MIN 0, 255, 255
#define COLOR_VU_MAX 255, 40, 120
#define COLOR_CLOCK 0, 255, 255
#define COLOR_CLOCK_BG 8, 18, 48
#define COLOR_SECONDS 255, 200, 0
#define COLOR_DAY_OF_W 160, 220, 255
#define COLOR_DATE 160, 220, 255
#define COLOR_HEAP 80, 110, 140
#define COLOR_BUFFER 80, 110, 140
#define COLOR_IP 160, 220, 255
#define COLOR_VOLUME_VALUE 160, 220, 255
#define COLOR_RSSI 160, 220, 255
#define COLOR_BITRATE 0, 255, 255
#define COLOR_VOLBAR_OUT 0, 255, 255
#define COLOR_VOLBAR_IN 8, 18, 48
#define COLOR_PL_CURRENT 0, 255, 255
#define COLOR_PL_CURRENT_BG 8, 18, 48
#define COLOR_PL_CURRENT_FILL 8, 18, 48
#define COLOR_PLAYLIST_0 160, 220, 255
#define COLOR_PLAYLIST_1 120, 180, 220
#define COLOR_PLAYLIST_2 80, 140, 190
#define COLOR_PLAYLIST_3 60, 110, 160
#define COLOR_PLAYLIST_4 40, 80, 120
#endif
